apiVersion: autoscaling/v1
kind: HorizontalPodAutoscalar
metadata:
  name: nodeapp-autoscale
  app: nodeapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodeapp-deployment
  minReplicas: 10
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50  
    
      