apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodeapp
  name: nodeapp-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - image: hellcaster/nodejs-test:latest
        name: nodeserver
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 500m
